### ISSUE TITLE
change relay.py to views.py

### ISSUE THREAD

**Issue by EricSchles** [heatseeknyc/relay#12]
Typically views.py is used for any controller code facing an end user.  This is canonical and will lead to less confusion for people new to the project and looking to contribute

**Comment by hrldcpr** [comment]
Thanks Eric, it used to be called that but it got kind of big so I split it into two separate files—`relay.py` and `setup.py`. So perhaps it would be clearer if we put them in a package, i.e. `views/relay.py` and `views/setup.py`?

**Comment by EricSchles** [comment]
Totally a good idea!
