### ISSUE TITLE
relay server went all the way down

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/relay#14]
The relay server was not just 504ing but instead was actually not resolving at all. We were getting a chrome ERR_NAME_NOT_RESOLVED page. Restarting fixed it but that seems like it isn't related to the issues we've seen in the past. What caused it to go down and what should we do about it?

**Comment by hrldcpr** [comment]
That error indicates a DNS problem, so either your internet was misbehaving or digitalocean was misbehaving, either way there's nothing we can do about it :sob:
