### ISSUE TITLE
tool or instructions for adding v1.5 xbees

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/relay#18]
We have a [couple dozen xbees running v1.5](https://docs.google.com/spreadsheets/d/10OW6EFgvvggHuP6uo2J_35ZiQDwUKKmSnLptmN7VP5s/edit#gid=786798945) and need a way to register them. A user interface would be awesome. A script would work too and be a lot faster to make. We'd probably want it to accept a CSV. As a stopgap, what is the SQL command you use to do this?

**Comment by williamcodes** [comment]
Hmm, looks like this is a duplicate of #17. My memory is shockingly bad.

**Comment by williamcodes** [comment]
But wait, this _is_ a separate issue! How do you add the version? The other comment was about adding xbees for hubs, not xbees for v1.5 cells.

**Comment by hrldcpr** [comment]
```
insert into cells (id, version) values ('0013a20040c17fb8', 'v0.5');
```
