### ISSUE TITLE
is this a range issue?

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/relay#23]
This cell is getting intermittent readings:

http://relay.heatseeknyc.com/cells/0013a20040b9e398

It was getting readings consistently every 10 seconds while in setup mode, and according to the person who did the install, she didn't move it after she switched it to live mode, which leads me to believe it's not out of range. Any theories as to why it's not more consistent?

**Comment by hrldcpr** [comment]
Very strange :sob: No idea other than range or interference or some sort of hub funkiness, sorry. Closing this for now since I looked through the relay logs and it doesn't seem like there's any issues there.
