### ISSUE TITLE
post to heatseek.org instead of heatseeknyc.com

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/relay#25]
We need to post to heatseek.org instead of heatseeknyc.com because heatseeknyc.com is going to be returning 301 redirects to the new domain name. This appears to prevent new readings from being created.

**Comment by hrldcpr** [comment]
Just replace `heatseeknyc.com` with `heatseek.org` in `batch.py` and you should be good 🌴

**Comment by williamcodes** [comment]
closed by #26
