### ISSUE TITLE
figure out why the relay server is still posting to old url

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/relay#27]
Once I set the heatseeknyc.com domain to forward to heatseek.org, the readings stop coming through. I tried restarting the batch process and restarting the entire relay server. Baffling. Thoughts @hrldcpr ?

**Comment by hrldcpr** [comment]
Did you rebuild the docker image?
I'm afk right now, but there should be instructions in the relay readme.

**Comment by williamcodes** [comment]
No, that's probably what I was missing. This is what the readme has:

```
$ docker build --pull --tag app app
$ sudo systemctl restart app
```

So I'm trying this:

```
$ docker build --pull --tag batch batch
```

That doesn't seem to be working. Looks like the `--pull` flag gets the latest version of the image, so that makes sense. the `--tag` part is the "Repository name (and optionally a tag) for the image" and the final input is the URL or PATH. The path seems like perhaps the part I'm getting wrong. There's no folder here for `batch`, just for `app`. Let's try this:

```
$ docker build --pull --tag batch app
```

Okay that seems to have built successfully. Let's try restarting:

```
$ sudo systemctl restart app
```

Hmm, this is taking longer than usual. I suppose that's promising. Let's try forwarding the domain name again and see if we get errors. Currently we're getting lots of readings on the app server, which means the relay is sending successfully. adding the following to `/opt/nginx/nginx.conf`:

```
    server {
            listen 80;
            listen 443 ssl;
            server_name www.heatseeknyc.com heatseeknyc.com;
            return 301 $scheme://www.heatseek.org$request_uri;
    }
```

Restarting the nginx server:

```
$ sudo nginx -s reload
```

Okay, heatseeknyc.com appears to be successfully forwarding to heatseek.org in Chrome. Let's check the logs to make sure the readings from the relay server are still coming through.

Crap. There are no more readings coming in on the app server nginx log file. It seems like the redirect is preventing any readings from coming through. Perhaps I didn't rebuild the docker image properly? What are your thoughts @hrldcpr?

**Comment by hrldcpr** [comment]
Yeah, the `batch` module doesn't have its own docker image, unlike most of the other modules. Definitely a bit confusing, I'll see if I can add some clarification to the readme. You could maybe guess this by the fact that the module is inside the `app/` directory, at `app/batch.service`, or you can know for sure by looking at the contents of `app/batch.service`, in which the commands use the `app` docker image.

So anyway, to update the `batch` module, you have to rebuild the `app` image:

```
docker build --pull --tag app app
sudo systemctl restart batch
```

I won't run that because I'm not sure what the state of the domains is, but that should work!

**Comment by williamcodes** [comment]
Excellent, worked like a charm. Thanks Harold!
