### ISSUE TITLE
Hub 6AF8 never registers with the relay server

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/relay#5]
The modem appears to connect, albeit not terribly quickly. Once it's connected though, it never registers with the relay server. I checked to see if it was registering with the wrong xbee id, but it's not. I tried flashing the SD card, and that didn't fix it either. The power supply is clearly fine. Could there be a problem on the relay server? The xbee is mounted properly. I can try swapping out the xbee or its mount, but it doesn't seem like that would interfere with its ability to set up a reverse tunnel.

**Comment by hrldcpr** [comment]
Looks like this got fixed, one way or another - http://relay.heatseeknyc.com/hubs/6af8
